//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelmangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_reserve
    {
        public int IDX { get; set; }
        public string cardID { get; set; }
        public string name { get; set; }
        public string roomID { get; set; }
        public string remark { get; set; }
    }
}
